stages:
  - install
  - test

install:
  stage: install
  image: golang:latest

  before_script:
    - go version
    - go mod download

  script:
    - go install

test:
  stage: test
  image: golang:latest

  before_script:
    - go version
    - go mod download

  script:
    - go run main.go "#FFFFFF" "#FFFFFF" "#FFFFFF" "#FFFFFF" "#FFFFFF" "#FFFFFF" 0 0 0 0 0
    - mv goout.png $CI_PROJECT_DIR/goout.png

  artifacts:
    paths:
      - goout.png