stages:
  - install
  - test

install:
  stage: install
  image: golang:latest

  before_script:
    - go version
    - go mod download

  script:
    - go install

test:
  stage: test
  image: golang:latest

  before_script:
    - go version
    - go mod download

  script:
    - go test -v ./...