stages:
  - test

install:
  stage: install
  image: golang:latest

  before_script:
    - go mod download

  script:
    - go run main.go "#FFFFFF" "#FFFFFF" "#FFFFFF" "#FFFFFF" "#FFFFFF" "#FFFFFF" 0 0 0 0 0

  artifacts:
    paths:
      - goout.png
