name: Renderer Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Fn CLI
        run: curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh

      - name: Install dependencies
        run: go mod download

      - name: Run Fn Project tests
        run: fn test
