name: Fn Project Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Install Fn Project CLI
      run: |
        curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh

    - name: Start Fn Server
      run: fn start &

    - name: Create Fn App
      run: fn create app goapp

    - name: Deploy Fn App
      run: fn --verbose deploy --app goapp --local

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Test Fn Function
      id: test-function
      run: |
        result=$(echo -n '{"avatarJSON":"","size":512}' | fn invoke goapp render --content-type application/json)
        echo "::set-output name=image::$(echo $result | jq -r '.image')"

    - name: Store JSON result
      run: |
        echo '${{ steps.test-function.outputs.image }}' > image.txt

    - name: Upload JSON artifact
      uses: actions/upload-artifact@v3
      with:
        name: function-result
        path: image.txt

    - name: Stop Fn Server
      run: fn stop
      if: always()
